brew 'rbenv'
brew 'pyenv'
brew 'tig'
brew  'marp-cli'
brew 'qrencode'
brew 'xcodes'
brew  'aria2'
brew 'git-lfs'
brew 'openjdk'
brew 'openjdk@17'
brew 'ffmpeg'
brew 'mint'
brew 'xcbeautify'
brew 'docker'

cask_args appdir: "/Applications"
cask 'google-chrome'
cask '1password'
cask 'discord'
cask 'charles'
cask 'iterm2'
cask 'postman'
cask 'brackets'
cask 'visual-studio-code'
cask 'rectangle'
cask 'docker-desktop'
cask 'sublime-merge'