brew 'rbenv'
brew 'tig'

cask_args appdir: "/Applications"
cask 'google-chrome'
cask 'slack'
cask 'spotify'
cask '1password'
cask 'notion'
cask 'discord'
cask 'charles'
cask 'iterm2'
cask 'postman'
cask 'lepton'
cask 'brackets'
cask 'visual-studio-code'
cask 'rectangle'